#!/usr/bin/env bash
HOST=22ftplink.ddns.net
USER=guest
PASS=guest



  if [ -d world ]; then  
    cd world
ftp -inv $HOST << EOF
user $USER $PASS
mput *
bye

EOF
  else
    mkdir -p world
    cd world
wget -nH --cut-dirs=1 ftp://22ftplink.ddns.net/* --ftp-user="guest" --ftp-password="guest" -r
  fi