#!/usr/bin/env bash
HOST='22ftplink.ddns.net'
USER='mcsync'
PASS='mcsync'

  if [ -d world ]; then  
  jar -cf worldsync.zip world
  curl -T worldsync.zip 'ftp://22ftplink.ddns.net/mcworld'
  else
  unzip world.zip
  fi
