#!/bin/bash
HOST=22ftplink.ddns.net
USER=admin
PASS=22f_tplink



  if [ -d world ]; then  
    cd world
ftp -inv $HOST << EOF
user $USER $PASS
cd 02DA-A3F3/mcworld/world/
mput *
bye

EOF
  else
    mkdir -p world
    cd world
wget -nH --cut-dirs=3 ftp://22ftplink.ddns.net/02DA-A3F3/mcworld/world/* --ftp-user="admin" --ftp-password="22f_tplink" -r
  fi